name = "DispatchSolvers"
uuid = "a15b4d3b-3cc7-4d6d-8034-cfac5534149a"
version = "0.1.0"
authors = ["v <vhsoo@proton.me>"]

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
